INSERT INTO krc353_1.Within (CID, DName) VALUES (1, 'Computer Science');
INSERT INTO krc353_1.Within (CID, DName) VALUES (2, 'Physics');
INSERT INTO krc353_1.Within (CID, DName) VALUES (3, 'French');
INSERT INTO krc353_1.Within (CID, DName) VALUES (4, 'Gender Studies');
INSERT INTO krc353_1.Within (CID, DName) VALUES (5, 'Biology');
INSERT INTO krc353_1.Within (CID, DName) VALUES (6, 'Mathematics');
INSERT INTO krc353_1.Within (CID, DName) VALUES (7, 'History');
INSERT INTO krc353_1.Within (CID, DName) VALUES (8, 'Engineering');
INSERT INTO krc353_1.Within (CID, DName) VALUES (9, 'Anthropology');
INSERT INTO krc353_1.Within (CID, DName) VALUES (10, 'Jewish Studies');