INSERT INTO krc353_1.Department (DName, Building) VALUES ('Anthropology', 'I Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Biology', 'C Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Computer Science', 'A Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Engineering', 'E Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('French', 'F Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Gender Studies', 'G Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('History', 'H Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Jewish Studies', 'J Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Mathematics', 'B Building');
INSERT INTO krc353_1.Department (DName, Building) VALUES ('Physics', 'D Building');